import * as ChatApp from '@/src/assets/projects/chatApp';
import * as TWatch from '@/src/assets/projects/tWatch';
import * as Collaboard from '@/src/assets/projects/collaboard';

export const projectsData = [
  {
    title: 'Chat Application',
    type: 'Desktop Application',
    date: 'March 2025',
    description: 'A real-time chat desktop application in Java, featuring multi-user messaging, live updates, and a user-friendly interface.',
    demoLink: '',
    src: 'https://github.com/JamJam126/Chat-Application',
    thumbnail: ChatApp.ChatAppThumb,
    thumbnailBackground: ChatApp.ChatAppThumbBg,
    images: [
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773726868/chatApp-1_eehczo.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773726868/chatApp-2_osm0dd.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773726869/chatApp-3_ag4bom.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773726869/chatApp-4_y6wgky.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773726869/chatApp-5_t57kwl.png',
    ],
  },
  {
    title: 'T Watch',
    type: 'E-commerce Website',
    date: 'March 2025',
    description: 'An E-commerce website that sell watches, straps and accessories.',
    demoLink: '',
    src: 'https://github.com/sokundeny/T_WATCH',
    thumbnail: TWatch.TWatchThumb,
    thumbnailBackground: TWatch.TWatchThumbBg,
    images: [
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727363/tWatch-1_swy9uq.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727358/tWatch-2_dcchxb.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727355/tWatch-3_bq6sqm.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727355/tWatch-4_ucw2wt.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727358/tWatch-5_ykvhxv.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727356/tWatch-6_yj1hcl.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727356/tWatch-7_iuktxm.png',
    ],
  },
  {
    title: 'Collaboard',
    type: 'Web Application',
    date: 'March 2025',
    description: 'A real-time chat desktop application in Java, featuring multi-user messaging, live updates, and a user-friendly interface.',
    demoLink: '',
    src: 'https://github.com/JamJam126/Collaboard',
    thumbnail: Collaboard.CollaboardThumb,
    thumbnailBackground: Collaboard.CollaboardThumbBg,
    images: [
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-1_ldmhda.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-2_fazlzs.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-3_qlxqhh.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-4_gmcdvj.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-5_atfvxm.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727752/collaboard-6_klw2zd.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727753/collaboard-7_bf0iwk.png',
    ],
  },
  {
    title: 'Collaboard',
    type: 'Web Application',
    date: 'March 2025',
    description: 'A real-time chat desktop application in Java, featuring multi-user messaging, live updates, and a user-friendly interface.',
    demoLink: '',
    src: 'https://github.com/JamJam126/Collaboard',
    thumbnail: Collaboard.CollaboardThumb,
    thumbnailBackground: Collaboard.CollaboardThumbBg,
    images: [
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-1_ldmhda.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-2_fazlzs.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-3_qlxqhh.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-4_gmcdvj.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727751/collaboard-5_atfvxm.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727752/collaboard-6_klw2zd.png',
      'https://res.cloudinary.com/dsdgi7f7f/image/upload/v1773727753/collaboard-7_bf0iwk.png',
    ],
  },
];